build_binary:
    builder: 'aws esp32'
    pre_flight: 'rm -rf $AMAZON_FREERTOS_PATH/demos/ && mv $SPN_PROJECT_DIR/aws_freertos_app $AMAZON_FREERTOS_PATH/demos'
    script: 'cd $AMAZON_FREERTOS_PATH/demos/espressif/esp32_devkitc_esp_wrover_kit/make/ && make && mv build/aws_demos.bin /tmp/aws_demos.bin'
    binary_name: '/tmp/aws_demos.bin'
    
# build_binary:
#     builder: 'particle'
#     binary_name: 'firmware/target/firmware.bin'
#     script: cd $SPN_BUILDER_SDK && make PLATFORM=electron APPDIR=$SPN_PROJECT_DIR/firmware
    
# testing:
#     script: testing/sample-test-script.py
#     env_vars:
#         - $electronDev1
#     device_update:
#         devices:
#             - $electronDev1
#         ota_method: "particle"
#         access_token: $PARTICLE_TOKEN
#         binary: "auto"
